import io
import wave
from piper import PiperVoice


_voice = None

def load_voice(voice_path: str = "voices/de_DE-thorsten-medium.onnx"):
    """Load the voice to use with Piper TTS for speech generation.

    Args:
        voice_path (str, optional): path to the audio file for Piper TTS, defaults to "voices/de_DE-thorsten-medium.onnx"

    Returns:
        PiperVoice: voice from Piper TTS used for audio
    """
    global _voice
    if _voice is None:
        _voice = PiperVoice.load(voice_path)
    return _voice


def text_to_speech_bytes(text: str) -> bytes:
    """Return WAV audio bytes generated by Piper TTS.

    Args:
        text (str): text input for TTS

    Returns:
        bytes: Piper WAV audio bytes
    """
    voice = load_voice()
    buffer = io.BytesIO()
    
    # Stream from Piper
    generator = voice.synthesize(text)

    # Get the first audio chunk
    try:
        first_chunk = next(generator)
    except StopIteration:
        return b""  # no audio

    # Open wave writer and set audio parameters using the first chunk
    with wave.open(buffer, "wb") as wav_file:
        wav_file.setnchannels(first_chunk.sample_channels)
        wav_file.setsampwidth(first_chunk.sample_width)
        wav_file.setframerate(first_chunk.sample_rate)

        # Write first chunk
        wav_file.writeframes(first_chunk.audio_int16_bytes)

        # Write remaining chunks
        for chunk in generator:
            wav_file.writeframes(chunk.audio_int16_bytes)

    return buffer.getvalue()
